version: "3.7"

services:
    next:
        environment:
            - PB_URL=http://127.0.0.1:8090
        image: zrafaf/educa_utf_nextjs:latest
        restart: unless-stopped
        ports:
            - 3000:3000

    pocketbase:
        image: augustodelg/pocketbase:latest
        restart: unless-stopped
        ports:
            - 8090:8090
        volumes:
            - pocketbase-volume:/pb_data
            - pocketbase-volume:/pb_hooks
volumes:
    pocketbase-volume:
