# Copyright (c) 2023 Rafael Farias
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

name: Check Release
on:
    pull-request:
        branches:
            - release
jobs:
    check-release:
        runs-on: ubuntu-latest
        steps:
            - uses: Slashgear/action-check-pr-title@v4.3.0
              with:
                  regexp: "v\d+\.\d+\.\d+" # Regex the title should match.
                  helpMessage: "Example: 'v1.2.3'"
