# Copyright (c) 2023 Rafael Farias
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

name: ci
on:
    push:
        branches:
            - main
permissions:
    contents: write
jobs:
    deploy:
        env:
            ENABLE_PDF_EXPORT: 1
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: 3.x
            - name: Install dependencies
              run: |
                  npm install
                  pip install -r docs/requirements.txt
            - uses: actions/cache@v2
              with:
                  key: ${{ github.ref }}
                  path: .cache
            - name: Build
              run: |
                  npm run build
            - name: Build documentation
              run: |
                  mkdocs build
                  ls
                  mv -v ./documentacao ./build/
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              # If you're changing the branch from main,
              # also change the `main` in `refs/heads/main`
              # below accordingly.
              if: ${{ github.ref == 'refs/heads/main' }}
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./build
