name: PR Title Check

on:
    pull_request:
        types:
            - opened
            - synchronize
            - edited
        branches:
            - release

jobs:
    title_check:
        runs-on: ubuntu-latest

        steps:
            - name: Check PR Title
              env:
                  TITLE: ${{ github.event.pull_request.title }}

            - uses: Slashgear/action-check-pr-title@v4.3.0
              with:
                  regexp: "v\d+\.\d+\.\d+" # Regex the title should match.
                  helpMessage: "Example: 'feat: example of title'"
