name: PR Title Check

on:
    pull_request:
        types:
            - opened
            - synchronize
            - edited
        branches:
            - release

jobs:
    title_check:
        runs-on: ubuntu-latest
        env:
            ACTIONS_STEP_DEBUG: true
        steps:
            - name: Check PR Title
              env:
                  TITLE: ${{ github.event.pull_request.title }}
              id: check-tag
              run: |
                  if [[ ${{ github.event.pull_request.title }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
                      echo "match=true" >> $GITHUB_OUTPUT
                  fi
