name: PR Title Check

on:
    pull_request:
        types:
            - opened
            - synchronize
            - edited
        branches:
            - release

jobs:
    title_check:
        runs-on: ubuntu-latest
        env:
            ACTIONS_STEP_DEBUG: true
        steps:
            - name: Check PR Title
              env:
                  TITLE: ${{ github.event.pull_request.title }}
            - uses: actions-ecosystem/action-regex-match@v2
              id: regex-match
              with:
                  text: ${{ github.event.pull_request.title }} # e.g. "Test: AB#16845 try to return PR number"
                  regex: 'v\d+\.\d+\.\d+'
