name: PR Title Check

on:
    pull_request:
        types:
            - opened
            - synchronize
            - edited
        branches:
            - release

jobs:
    title_check:
        runs-on: ubuntu-latest
        env:
            ACTIONS_STEP_DEBUG: true
        steps:
            - uses: actions/checkout@v1
            - uses: dylanvann/check-pull-request-title@v0
              with:
                  # Match pull request titles in the form UI-1234 - Message.
                  pattern: 'v\d+\.\d+\.\d+'
