# Copyright (c) 2023 Rafael Farias
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

name: Release container
on:
    push:
        branches:
            - release
jobs:
    publish-container:
        runs-on: ubuntu-latest
        steps:
            - name: Get pr
              uses: 8BitJonny/gh-get-current-pr@2.2.0
              id: PR
              run: echo "Your PR number is ${{ steps.PR.outputs.number }} and its JSON is ${{ steps.PR.outputs.pr }}"
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build Docker image
              run: docker build -t educa_utf_nextjs .
            - name: Add tags to image
              env:
                  TITLE: ${{ steps.PR.outputs.pr_title }}
              run: |
                  docker tag educa_utf_nextjs zrafaf/educa_utf_nextjs:$TITLE
                  docker tag educa_utf_nextjs zrafaf/educa_utf_nextjs
            - name: Push Docker image
              run: |
                  docker push zrafaf/educa_utf_nextjs:$TITLE
                  docker push zrafaf/educa_utf_nextjs
