# Copyright (c) 2023 Rafael Farias
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

name: Release container
on:
    push:
        branches:
            - release
jobs:
    publish-container:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build Docker image
              run: docker build -t educa_utf_nextjs .
            - name: Add tags to image
              env:
                  TITLE: ${{ github.event.pull_request.title }}
              run: |
                  docker tag educa_utf_nextjs zrafaf/educa_utf_nextjs:$TITLE
                  docker tag educa_utf_nextjs zrafaf/educa_utf_nextjs
            - name: Push Docker image
              run: |
                  docker push zrafaf/educa_utf_nextjs:$TITLE
                  docker push zrafaf/educa_utf_nextjs
